let dummyData = {
  queryCost: 73,
  latitude: 35.6841,
  longitude: 139.809,
  resolvedAddress: 'Tokyo, Japan',
  address: 'tokyo',
  timezone: 'Asia/Tokyo',
  tzoffset: 9,
  description:
    'Similar temperatures continuing with a chance of rain multiple days.',
  days: [
    {
      datetime: '2024-08-23',
      datetimeEpoch: 1724338800,
      tempmax: 88.2,
      tempmin: 81.4,
      temp: 84.4,
      feelslikemax: 100.5,
      feelslikemin: 88.2,
      feelslike: 94.1,
      dew: 76.8,
      humidity: 78.3,
      precip: 0.004,
      precipprob: 100,
      precipcover: 4.17,
      preciptype: ['rain'],
      snow: 0,
      snowdepth: 0,
      windgust: 21.7,
      windspeed: 18,
      winddir: 177,
      pressure: 1011.8,
      cloudcover: 58.5,
      visibility: 6.6,
      solarradiation: 235.4,
      solarenergy: 20.3,
      uvindex: 7,
      severerisk: 30,
      sunrise: '05:05:54',
      sunriseEpoch: 1724357154,
      sunset: '18:20:24',
      sunsetEpoch: 1724404824,
      moonphase: 0.62,
      conditions: 'Rain, Partially cloudy',
      description: 'Clearing in the afternoon with morning rain.',
      icon: 'rain',
      stations: ['RJTY', 'RJTI', 'RJTF', 'RJTT', 'RJAA'],
      source: 'obs',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1724338800,
          temp: 81.6,
          feelslike: 88.9,
          humidity: 84.73,
          dew: 76.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.5,
          windspeed: 14.4,
          winddir: 171,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 76.6,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1724342400,
          temp: 81.5,
          feelslike: 88.5,
          humidity: 84.51,
          dew: 76.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 18.6,
          windspeed: 12.2,
          winddir: 172,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 79.8,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1724346000,
          temp: 81.4,
          feelslike: 88.2,
          humidity: 84.11,
          dew: 76.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 19.2,
          windspeed: 13.1,
          winddir: 179,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1724349600,
          temp: 82,
          feelslike: 90,
          humidity: 84.15,
          dew: 76.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 18.3,
          windspeed: 14.3,
          winddir: 180,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 88.9,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1724353200,
          temp: 82,
          feelslike: 90,
          humidity: 84.15,
          dew: 76.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 17,
          windspeed: 14.2,
          winddir: 186,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1724356800,
          temp: 81.8,
          feelslike: 88.5,
          humidity: 80.76,
          dew: 75.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 17.7,
          windspeed: 13.4,
          winddir: 158,
          pressure: 1012.2,
          visibility: 6.7,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1724360400,
          temp: 81.8,
          feelslike: 89.4,
          humidity: 84.14,
          dew: 76.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 16.8,
          windspeed: 14.7,
          winddir: 173,
          pressure: 1012.2,
          visibility: 6.7,
          cloudcover: 83.1,
          solarradiation: 31,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1724364000,
          temp: 82.2,
          feelslike: 90.2,
          humidity: 83.56,
          dew: 76.7,
          precip: 0.004,
          precipprob: 100,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 13.9,
          windspeed: 13.5,
          winddir: 157,
          pressure: 1012.2,
          visibility: 6.7,
          cloudcover: 32.5,
          solarradiation: 183,
          solarenergy: 0.7,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1724367600,
          temp: 83.8,
          feelslike: 93.1,
          humidity: 79.39,
          dew: 76.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.2,
          windspeed: 13.4,
          winddir: 178,
          pressure: 1012.2,
          visibility: 6.7,
          cloudcover: 83.1,
          solarradiation: 329,
          solarenergy: 1.2,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1724371200,
          temp: 85.9,
          feelslike: 98.3,
          humidity: 77.76,
          dew: 78.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.3,
          windspeed: 10,
          winddir: 182,
          pressure: 1012,
          visibility: 6.3,
          cloudcover: 58.2,
          solarradiation: 461,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1724374800,
          temp: 86.4,
          feelslike: 97.8,
          humidity: 73.64,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.9,
          windspeed: 12.6,
          winddir: 167,
          pressure: 1012,
          visibility: 6.3,
          cloudcover: 82.5,
          solarradiation: 685,
          solarenergy: 2.5,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1724378400,
          temp: 87.8,
          feelslike: 100,
          humidity: 70.41,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 11.2,
          windspeed: 12.2,
          winddir: 180,
          pressure: 1012,
          visibility: 6.3,
          cloudcover: 53.6,
          solarradiation: 708,
          solarenergy: 2.5,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1724382000,
          temp: 88.2,
          feelslike: 100.5,
          humidity: 69.6,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 16.1,
          windspeed: 15.9,
          winddir: 172,
          pressure: 1011.9,
          visibility: 6.3,
          cloudcover: 32.3,
          solarradiation: 482,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1724385600,
          temp: 87.8,
          feelslike: 99.6,
          humidity: 69.65,
          dew: 76.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 15.9,
          windspeed: 15.1,
          winddir: 180,
          pressure: 1011,
          visibility: 6.3,
          cloudcover: 31,
          solarradiation: 547,
          solarenergy: 2,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1724389200,
          temp: 88,
          feelslike: 99.9,
          humidity: 69.58,
          dew: 76.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 14.8,
          windspeed: 14.6,
          winddir: 179,
          pressure: 1011,
          visibility: 6.3,
          cloudcover: 28.7,
          solarradiation: 736,
          solarenergy: 2.6,
          uvindex: 7,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1724392800,
          temp: 87.8,
          feelslike: 100,
          humidity: 70.45,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 13.6,
          windspeed: 13.8,
          winddir: 179,
          pressure: 1011,
          visibility: 6.3,
          cloudcover: 27.9,
          solarradiation: 637,
          solarenergy: 2.3,
          uvindex: 6,
          severerisk: 30,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1724396400,
          temp: 87.6,
          feelslike: 99.6,
          humidity: 71.09,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 15.7,
          windspeed: 12.6,
          winddir: 180,
          pressure: 1010.9,
          visibility: 6.3,
          cloudcover: 27.9,
          solarradiation: 479,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 30,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTI', 'RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1724400000,
          temp: 86.3,
          feelslike: 97.4,
          humidity: 73.66,
          dew: 76.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 17.7,
          windspeed: 16.9,
          winddir: 176,
          pressure: 1011,
          visibility: 6.5,
          cloudcover: 37.1,
          solarradiation: 280,
          solarenergy: 1,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTY', 'RJTF', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1724403600,
          temp: 84,
          feelslike: 93.5,
          humidity: 78.84,
          dew: 76.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.1,
          windspeed: 18,
          winddir: 180,
          pressure: 1011,
          visibility: 6.7,
          cloudcover: 45.1,
          solarradiation: 92,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1724407200,
          temp: 83.6,
          feelslike: 92.8,
          humidity: 79.74,
          dew: 76.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.6,
          windspeed: 16.5,
          winddir: 178,
          pressure: 1011.1,
          visibility: 6.7,
          cloudcover: 28,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 3,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1724410800,
          temp: 83.5,
          feelslike: 94.1,
          humidity: 84.24,
          dew: 78.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 21,
          windspeed: 14.2,
          winddir: 180,
          pressure: 1012,
          visibility: 6.7,
          cloudcover: 48.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1724414400,
          temp: 83.5,
          feelslike: 92.7,
          humidity: 80.31,
          dew: 76.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.6,
          windspeed: 15.2,
          winddir: 188,
          pressure: 1012,
          visibility: 6.7,
          cloudcover: 83.1,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1724418000,
          temp: 83.3,
          feelslike: 92.3,
          humidity: 80.87,
          dew: 76.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.4,
          windspeed: 15.2,
          winddir: 188,
          pressure: 1012.1,
          visibility: 6.7,
          cloudcover: 29.9,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1724421600,
          temp: 83.7,
          feelslike: 93.3,
          humidity: 80.32,
          dew: 77,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 21.7,
          windspeed: 15.2,
          winddir: 181,
          pressure: 1012,
          visibility: 6.7,
          cloudcover: 81.4,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['RJTY', 'RJTT', 'RJAA'],
          source: 'obs',
        },
      ],
    },
  ],
  alerts: [],
  stations: {
    AS392: {
      distance: 17867,
      latitude: 35.845,
      longitude: 139.802,
      useCount: 0,
      id: 'AS392',
      name: 'JH4XSY-13 Soka City JP',
      quality: 0,
      contribution: 0,
    },
    F7254: {
      distance: 27535,
      latitude: 35.57,
      longitude: 139.539,
      useCount: 0,
      id: 'F7254',
      name: 'FW7254 Yokohama JP',
      quality: 0,
      contribution: 0,
    },
    RJTY: {
      distance: 42129,
      latitude: 35.75,
      longitude: 139.35,
      useCount: 0,
      id: 'RJTY',
      name: 'RJTY',
      quality: 48,
      contribution: 0,
    },
    RJTI: {
      distance: 7073,
      latitude: 35.63,
      longitude: 139.85,
      useCount: 0,
      id: 'RJTI',
      name: 'RJTI',
      quality: 17,
      contribution: 0,
    },
    RJTF: {
      distance: 25278,
      latitude: 35.67,
      longitude: 139.53,
      useCount: 0,
      id: 'RJTF',
      name: 'RJTF',
      quality: 18,
      contribution: 0,
    },
    RJTT: {
      distance: 16254,
      latitude: 35.54,
      longitude: 139.78,
      useCount: 0,
      id: 'RJTT',
      name: 'RJTT',
      quality: 50,
      contribution: 0,
    },
    RJAA: {
      distance: 52480,
      latitude: 35.77,
      longitude: 140.38,
      useCount: 0,
      id: 'RJAA',
      name: 'RJAA',
      quality: 50,
      contribution: 0,
    },
  },
  currentConditions: {
    datetime: '23:00:00',
    datetimeEpoch: 1724594400,
    temp: 83.6,
    feelslike: 94.4,
    humidity: 83.9,
    dew: 78.2,
    precip: null,
    precipprob: 0,
    snow: 0,
    snowdepth: 0,
    preciptype: null,
    windgust: null,
    windspeed: 13,
    winddir: 161,
    pressure: 1012,
    visibility: 6.2,
    cloudcover: 25,
    solarradiation: 0,
    solarenergy: 0,
    uvindex: 0,
    conditions: 'Partially cloudy',
    icon: 'partly-cloudy-night',
    stations: ['AS392', 'F7254', 'RJTT'],
    source: 'obs',
    sunrise: '05:08:12',
    sunriseEpoch: 1724616492,
    sunset: '18:16:27',
    sunsetEpoch: 1724663787,
    moonphase: 0.75,
  },
};
export default dummyData;
